# -*- coding: utf-8 -*-
"""punto38

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LQDuT7sKsI5jcylzIYoIVSw9FvmVkqtq
"""

from math import sin, cos, tan, exp, log

def calculator():
   
    funciones = {'sen':sin, 'cos':cos, 'tan':tan, 'exp':exp, 'log':log}
    f = input('Escoja la función a aplicar (sen, cos, tan, exp, log): ')
    n = int(input('Ingrese el numero a calcular: '))
    resultado = [funciones[f](x) for x in range(1, n+1)]
    for i in range(n):
        print (i + 1, '\t', resultado[i])
    return

calculator()