# -*- coding: utf-8 -*-
"""punto50

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

canasta = {}
opcion = 'Si'
while opcion == 'Si' :
    articulo = input('Ingrese un artículo: ')
    precio = float(input('Ingrese el precio de ' + articulo+ ': '))
    canasta[articulo] = precio
    opcion = input('¿Desea añadir más artículos a la lista (Si/No)? ')
total = 0
print('Lista de la compra')
for articulo, precio in canasta.items():
    print(articulo, '\t', precio)
    total += precio
print('El coste total fue: ', total)