# -*- coding: utf-8 -*-
"""punto44

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

opciones = {'Plátano':1.35, 'Manzana':0.8, 'Pera':0.85, 'Naranja':0.7}
fruta = input('¿Qué fruta quieres? ').title()
kg = float(input('¿Cuántos kilos? '))
if fruta in opciones:
    print(kg, 'kilos de', fruta, 'valen', opciones[fruta]*kg )
else: 
    print("Lo siento, la fruta", fruta, "no está disponible")