# -*- coding: utf-8 -*-
"""punto46

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

sexto_semestre = {'Electiva Profesional I': 3, 'Ingeniería de Software': 3, 'Sistemas de Comunicación': 4, 'Modelamiento de Sistemas': 3, 'Sistemas Distribuidos': 3, 'Democracia y Paz': 2}
total_creditos = 0
#(.items)Devuelve una lista de tuplas, cada tupla se compone de dos elementos: el primero será la clave y el segundo, su valor
for materia, creditos in sexto_semestre.items():
    print(materia, 'tiene', creditos, 'créditos')
    total_creditos += creditos
print('El número total de créditos para el 6 Semestre son: ', total_creditos)