# -*- coding: utf-8 -*-
"""punto28

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

def suma_digitos(ano): 
    ano = str(ano)
    suma = 0
    for i in ano:
        suma += int(i)
    return suma
  
print ("Calcular Año Bisiesto")
ano = int(input("Ingrese el año : "))


while not((ano % 4 == 0) and (ano % 100 != 0)) and (ano % 400 != 0):
  ano = ano + 1

print( "El próximo año bisiesto sería ", ano)
  
suma_dig = suma_digitos(ano)
suma_final = int(suma_dig)

print("La suma de los digitos del año bisiesto es :",suma_dig)