# -*- coding: utf-8 -*-
"""punto36

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

nombre = input("Ingrese su nombre: ")
apellido = input(f"Ingrese su primer apellido {nombre}: ")
print(f"{nombre}," ,apellido )