# -*- coding: utf-8 -*-
"""punto48

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

clientes = {}
opcion = ''
while opcion != '6':
    if opcion == '1':
        nif = input('Ingrese NIF del cliente: ')
        nombre = input('Ingrese el nombre del cliente: ')
        direccion = input('Ingrese la dirección del cliente: ')
        numero = input('Ingrese el teléfono del cliente: ')
        email = input('Ingrese el correo electrónico del cliente: ')
        vip = input('¿Es un cliente preferente s/n? ')
        cliente = {'nombre':nombre, 'dirección':direccion, 'teléfono':numero, 'email':email, 'preferente':vip=='s'}
        clientes[nif] = cliente
    if opcion == '2':
        nif = input('Ingrese NIF del cliente: ')
        if nif in clientes:
            del clientes[nif]
        else:
            print('No existe el cliente con el NIF', nif)
    if opcion == '3':
        nif = input('Ingrese NIF del cliente: ')
        if nif in clientes:
            print('NIF:', nif)
            for key, value in clientes[nif].items():
                print(key.title() + ':', value)
        else:
            print('No existe el cliente con el NIF', nif)
    if opcion == '4':
        print('Lista de clientes: ')
        for key, value in clientes.items():
            print(key, value['nombre'])
    if opcion == '5':
        print('Lista de clientes preferentes')
        for key, value in clientes.items():
            if value['preferente']:
                print(key, value['nombre'])
    opcion = input('Menú\n1. Añadir cliente\n2. Eliminar cliente\n3. Mostrar cliente\n4. Listar clientes\n5. Listar clientes preferentes\