# -*- coding: utf-8 -*-
"""punto42

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5LHW-p5l3H_GxN0nqdiyDFeUGY5j7ih
"""

def escalar(v):
  return sum([x ** 2 for x in v]) ** 0.5

print(escalar((1, 4)))
print(escalar((1, 2, 3)))