# -*- coding: utf-8 -*-
"""punto10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGNjxZmqQ9OcBgoDoYlPfpuXRuOPxCAn
"""

import random
letras = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","Ñ","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
aleatorio = []

def llenado():
  for i in range(1000):
    vector = letras[random.randrange(len(letras))]
    aleatorio.append(vector)
  print("ALFABETO: "+str(letras))
  return aleatorio

def contador(x):
  aux = []  
  print("vector aleatorio: "+str(x))
  for i in range(len(letras)):
    cont = 0
    for j in range(len(x)):
      if(letras[i] == x[j]):
        cont = cont +1
    aux.append(cont)
  return aux

def mostrar(x):
  aux1 = ""
  for i in range(len(letras)):
    aux1 = aux1+letras[i]
  prueba = dict(zip(aux1,x))
  print (prueba)
  
def control():
  aux2 = llenado()
  aux3 = contador(aux2)
  mostrar(aux3)
control()